import React,{useEffect,useState} from 'react'; import {createRoot} from 'react-dom/client'; import './style.css';
const API='http://localhost:5000/api';
function App(){
 const [context,setContext]=useState(null); const [result,setResult]=useState(null); const [loading,setLoading]=useState(false);
 const load=async()=>setContext((await (await fetch(API+'/context')).json()).data); useEffect(()=>{load()},[]);
 const simulate=async(type)=>{setLoading(true); const event={source:'ring',type,priority:type==='security_alert'?'critical':'medium',metadata:{location:'front_door'}}; const r=await fetch(API+'/events',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({event,context})}); setResult((await r.json()).data); setLoading(false)};
 const setAvailability=async(a)=>{await fetch(API+'/context',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({availability:a,activity:a==='busy'?'meeting':'idle'})});load()};
 return <main><header><div><span className="dot"/> AMBIENT</div><span className="muted">Context-aware agent prototype</span></header><section className="hero"><p className="eyebrow">THE ASSISTANT THAT KNOWS WHEN TO ACT</p><h1>Don't just understand the event.<br/><span>Understand the moment.</span></h1><p className="lead">Ambient receives device events, combines them with user context, and decides whether to act now, wait, or ignore.</p></section><div className="grid"><section className="card"><h2>Current context</h2><div className="context"><b>{context?.availability==='busy'?'🔴 Busy':'🟢 Available'}</b><span>{context?.activity}</span><span>{context?.location}</span></div><div className="actions"><button onClick={()=>setAvailability('busy')}>Start meeting</button><button onClick={()=>setAvailability('available')}>End meeting</button></div></section><section className="card"><h2>Simulate device event</h2><button className="primary" disabled={loading} onClick={()=>simulate('package_delivered')}>📦 Package delivered</button><button onClick={()=>simulate('security_alert')}>🚨 Security alert</button></section></div>{result&&<section className="decision"><div><p className="eyebrow">AGENT DECISION</p><h2>{result.decision.decision}</h2><p>{result.decision.reason}</p></div><div className="timeline"><div>📦 {result.event.type}</div><div>🧠 Context: {result.context.availability}</div><div>⚡ Action: {result.decision.decision}</div></div></section>}</main>}
createRoot(document.getElementById('root')).render(<App/>);
